---
title: "Question2"
author: "Zander Prinsloo"
date: "5/24/2021"
output:
  pdf_document: default
  html_document: default
---



```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5)
options(dplyr.summarise.inform=F)
if(!require("pacman")) install.packages("pacman")
library(pacman)
p_load(tidyverse)

list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
list.files('..//Question1/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
list.files('..//Question2/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
# Data loading:
df_forbes <- fn_Collate_Data(path = "/Users/zanderprinsloo/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Desktop – MacBookPro’s MacBook Pro/Academic/Postgraduate/Masters/Modules/Data Science/Test/20065124/data/Forbes/", ext = "csv")

```

# Task
Some interesting findings using the Forbes data set


# Plot 1

```{r Figure1, ,  warning =  FALSE, fig.align = 'center', fig.cap = "Names of Rich People \\label{Figure1}", fig.ext = 'png', fig.height = 3, fig.width = 6}

g1 <- plot1_Q2(df = df_forbes, title = "Common Names of Rich People", 
               Xlab = "Names", 
               Ylab = "Frequency of Names")
g1



```

This plot in \ref{Figure1} shows that there is a surprisingly high requency of rich people with names John, Mike/Michael, James, or Bill. Similarly, there are quite a number of families that make up the Billionaires on Forbes' list.



<!-- ```{r} -->
<!-- df_use <- df_forbes %>%  -->
<!--     mutate(Common = ifelse(grepl(pattern = "John|Mike|Michael|James|Bill", x = Name), 1, 0),  -->
<!--               Family = ifelse(grepl(pattern = "family", x = Name), 1, 0)) %>% -->
<!--     summarise(Type = ifelse(Common==1, "Common", ifelse(Family==1, "Family", "Neither"))) %>%  -->
<!--     group_by(Type) %>%  -->
<!--     summarise(Counts = n()) -->

<!-- ggplot(df_use, aes(x = Type, y = Counts)) + -->
<!--   geom_bar(fill = "#0073C2FF", stat = "identity") + -->
<!--   geom_text(aes(label = Counts), vjust = -0.3) +  -->
<!--   theme_bw() -->
<!-- ``` -->







